# Generated by Django 3.2.5 on 2021-07-28 18:51

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='produce_images')),
                ('produce_type', models.CharField(max_length=255)),
                ('produce_description', models.CharField(max_length=255)),
                ('produce_unit', models.CharField(choices=[('LT', 'Litres'), ('KG', 'Kilograms'), ('C', 'Crates'), ('E', 'Each')], max_length=2)),
                ('produce_price', models.IntegerField()),
                ('produce_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='profilepics')),
                ('name', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=1000)),
                ('profile_type', models.CharField(choices=[('FARMER', 'Farmer'), ('CONSUMER', 'Consumer')], max_length=255)),
                ('Phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='marketplace.produce')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
