# Generated by Django 3.2.5 on 2021-07-26 19:56

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produce_type', models.CharField(max_length=255)),
                ('produce_description', models.CharField(max_length=255)),
                ('produce_unit', models.CharField(choices=[('LT', 'Litres'), ('KG', 'Kilograms'), ('C', 'Crates'), ('E', 'Each')], max_length=2)),
                ('produce_price', models.CharField(max_length=255)),
                ('produce_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='profilepics')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=1000)),
                ('profile_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Farmer'), (2, 'consumer')], null=True)),
                ('Phone_number', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='marketplace.produce')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
