# Generated by Django 3.2.5 on 2021-07-27 18:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='produce_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='produce_images'),
        ),
    ]
