# Generated by Django 3.2.5 on 2021-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_produce_produce_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='produce',
            name='produce_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('CONSUMER', 'Consumer')], max_length=255),
        ),
    ]
