# Generated by Django 3.2.5 on 2021-07-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20210728_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='photo_url',
        ),
        migrations.AlterField(
            model_name='produce',
            name='produce_price',
            field=models.IntegerField(),
        ),
    ]
